name: Update Docker Hub README everytime it changes on master

on:
  push:
    branches:
      - master
    paths:
      - README.md
      - '.github/workflows/update-readme.yml'

jobs:
  sync:
    name: Update README to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.0.0
      - name: Sync README.md and Description to Docker Hub using meeDamian action (my fork)
        uses: nolim1t/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKER_USERNAME }}
          pass: ${{ secrets.DOCKER_PASSWORD }}
          description: true
